name = "Pipes"
version = "0.1.0"
keywords = ["pipes"]
defaultTargets = ["Pipes"]
leanOptions = { experimental.module = true }

[[lean_lib]]
name = "Pipes"
buildType = "relWithDebInfo"

[[require]]
name = "aesop"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/aesop"
#
# [[require]]
# name = "Canonical"
# scope = "chasenorman"
