name = "Pipes"
version = "0.1.0"
keywords = ["pipes"]
defaultTargets = ["Pipes"]
leanOptions = { experimental.module = true }

[[lean_lib]]
name = "Pipes"
buildType = "relWithDebInfo"

[[lean_exe]]
name = "PipesTest" # executable name
# main = "PipesTest.lean"      # path to the Lean file with main
buildType = "relWithDebInfo"

[[require]]
name = "aesop"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/aesop"

# [[require]]
# name = "Canonical"
# scope = "chasenorman"
